{% set version = '0.1.4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tiledb-jupyter-shiny
  version: {{ version|replace("-", "_") }}

source:

  git_url: https://github.com/TileDB-Inc/TileDB-Jupyter-Shiny
  git_tag: v0.1.4

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}filesystem        # [win]
    - {{posix}}git
    - {{posix}}zip               # [win]

  host:
    - r-base 3.6.*
    - r-irdisplay
    - r-callr
    - r-pingr
    - r-shiny

  run:
    - r-base 3.6.*
    - r-irdisplay
    - r-callr
    - r-pingr
    - r-shiny

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('tiledbJupyterShiny')"           # [not win]
    - "\"%R%\" -e \"library('tiledbJupyterShiny')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/TileDB-Inc/TileDB-Jupyter-Shiny
  license: MIT
  summary: Render Shiny apps inside a Jupyter notebook.

  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

# The original CRAN metadata for this package was:

# Package: tiledbJupyterShiny
# Type: Package
# Title: Render Shiny apps inside a Jupyter notebook
# Version: 0.1.4
# Author: TileDB
# Maintainer: TileDB <hello@tiledb.com>
# Description: Render Shiny apps inside a Jupyter notebook.
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# Imports: IRdisplay, shiny, callr, pingr
# Roxygen: list(markdown = TRUE)
# RoxygenNote: 7.1.1

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
