{% set name = "r-shiny-bg" %}
{% set version = "0.1.5" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/TileDB-Inc/shinybg/archive/v{{ version }}.tar.gz
  sha256: 779180fadd3dd00d736fb0b6fe75fa156a7d89c729153aee88c88ce50fc0c083

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}filesystem        # [win]
    - {{posix}}git
    - {{posix}}zip               # [win]
  host:
    - r-base 3.6.*
    - r-irdisplay
    - r-callr
    - r-pingr
    - r-shiny
  run:
    - r-base 3.6.*
    - r-irdisplay
    - r-callr
    - r-pingr
    - r-shiny

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('shinybg')"           # [not win]
    - "\"%R%\" -e \"library('shinybg')\""  # [win]

about:
  home: https://github.com/TileDB-Inc/shinybg
  license: MIT
  summary: Render Shiny apps inside a Jupyter notebook

  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - aaronwolen
    - ihnorton
    - SarantopoulosKon
    - Shelnutt2
